# Generated by Django 4.2.4 on 2023-08-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_remove_question_audio_src_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_id', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('policy_issue', models.CharField(max_length=50)),
                ('digital_adoption', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=50)),
                ('claim', models.CharField(max_length=20)),
                ('states', models.CharField(max_length=50)),
                ('commision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fraud_detected', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CrossSellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('agent_id', models.IntegerField()),
                ('speciality', models.CharField(max_length=50)),
                ('additional_households_with_vehicles', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
